/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Pos3D = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'z' : IDL.Float64,
});
export const Building = IDL.Record({ 'size' : Pos3D, 'position' : Pos3D });
export const Road = IDL.Record({
  'id' : IDL.Int,
  'name' : IDL.Text,
  'path' : IDL.Vec(Pos3D),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'color' : IDL.Text,
});
export const Character = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'color' : IDL.Text,
});
export const World = IDL.Record({
  'worldGeom' : IDL.Tuple(IDL.Vec(Building), IDL.Vec(Road)),
  'locationName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createWorld' : IDL.Func(
      [IDL.Text, IDL.Vec(Building), IDL.Vec(Road)],
      [],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlayerPosition' : IDL.Func(
      [IDL.Principal],
      [Pos3D, IDL.Float64, Character],
      ['query'],
    ),
  'getPlayers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Pos3D, IDL.Float64, Character))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorld' : IDL.Func([], [IDL.Opt(World)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinWorld' : IDL.Func([Character, Pos3D, IDL.Float64], [], []),
  'leaveWorld' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePosition' : IDL.Func([Pos3D, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Pos3D = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'z' : IDL.Float64,
  });
  const Building = IDL.Record({ 'size' : Pos3D, 'position' : Pos3D });
  const Road = IDL.Record({
    'id' : IDL.Int,
    'name' : IDL.Text,
    'path' : IDL.Vec(Pos3D),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'color' : IDL.Text });
  const Character = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'color' : IDL.Text,
  });
  const World = IDL.Record({
    'worldGeom' : IDL.Tuple(IDL.Vec(Building), IDL.Vec(Road)),
    'locationName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createWorld' : IDL.Func(
        [IDL.Text, IDL.Vec(Building), IDL.Vec(Road)],
        [],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlayerPosition' : IDL.Func(
        [IDL.Principal],
        [Pos3D, IDL.Float64, Character],
        ['query'],
      ),
    'getPlayers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Pos3D, IDL.Float64, Character))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorld' : IDL.Func([], [IDL.Opt(World)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinWorld' : IDL.Func([Character, Pos3D, IDL.Float64], [], []),
    'leaveWorld' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePosition' : IDL.Func([Pos3D, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };