/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Building { 'size' : Pos3D, 'position' : Pos3D }
export interface Character {
  'principal' : Principal,
  'name' : string,
  'color' : string,
}
export interface Pos3D { 'x' : number, 'y' : number, 'z' : number }
export interface Road { 'id' : bigint, 'name' : string, 'path' : Array<Pos3D> }
export interface UserProfile { 'name' : string, 'color' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface World {
  'worldGeom' : [Array<Building>, Array<Road>],
  'locationName' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createWorld' : ActorMethod<
    [string, Array<Building>, Array<Road>],
    undefined
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlayerPosition' : ActorMethod<[Principal], [Pos3D, number, Character]>,
  'getPlayers' : ActorMethod<[], Array<[Pos3D, number, Character]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorld' : ActorMethod<[], [] | [World]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinWorld' : ActorMethod<[Character, Pos3D, number], undefined>,
  'leaveWorld' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePosition' : ActorMethod<[Pos3D, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];